default: &global
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: warning


development:
  <<: *global
  database: redllantas_development

test:
  <<: *global
  database: redllantas_test